### ISSUE TITLE
lab file 05 wrong formatting

### ISSUE THREAD

**Issue by bckelly** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.zh-cn#1]
Looks like formatting on steps 5 and 6 are incorrect - they do not map to the English. In this language version, it looks like some text from step 5 needs to move to step 6

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Now, the locpage show correct.
https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.zh-cn/blob/OLPRODLOC/Instructions/Labs/LAB_05-Implement_Intersite_Connectivity.md

**Comment by chriscarty00** [comment]
Closing
